FROM public.ecr.aws/lambda/python:3.13

RUN dnf update -y

WORKDIR /var/task

COPY ./app.py ./
COPY ./utils ./utils/
COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

CMD ["app.lambda_handler"]